### ISSUE TITLE
Add support for adding additional repositories

### ISSUE THREAD

**Issue by neilenns** [office-tecoli/actions-use-apt-tools#7]
The apt package I'm installing is in a PPA repository. It'd be great if the action supported specifying a list of additional repositories to add prior to doing apt-install.

I managed to get this working by adding two steps prior to `install-and-archive` in the action:

```yaml
    - id: add-ppa-repository
      if: >-
        steps.cache.outputs.cache-hit != 'true' &&
        inputs.ppaRepositories
      shell: bash
      run: |
        for repo in ${{ inputs.ppaRepositories }}; do
          sudo add-apt-repository --yes --ppa $repo
        done

    - id: add-cloud-repository
      if: >-
        steps.cache.outputs.cache-hit != 'true' &&
        inputs.cloudRepositories
      shell: bash
      run: |
        for repo in ${{ inputs.cloudRepositories }}; do
          sudo add-apt-repository --yes --cloud $repo
        done
```

And used it like this:

```yaml
      - name: Install and cache KiCad
        uses: ./.github/actions/use-apt-tools
        id: apt-install
        with:
          ppaRepositories: >-
            ppa:kicad/kicad-9.0-releases
          tools: kicad
```
